//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.06.24 at 10:22:01 PM IST 
//


package com.hlc.TruckTrackPublisher.domain.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TmsMsg }
     * 
     */
    public TmsMsg createTmsMsg() {
        return new TmsMsg();
    }

    /**
     * Create an instance of {@link TmsMsg.Transaction }
     * 
     */
    public TmsMsg.Transaction createTmsMsgTransaction() {
        return new TmsMsg.Transaction();
    }

    /**
     * Create an instance of {@link TmsMsg.Transaction.Message }
     * 
     */
    public TmsMsg.Transaction.Message createTmsMsgTransactionMessage() {
        return new TmsMsg.Transaction.Message();
    }

    /**
     * Create an instance of {@link TmsMsg.Transaction.Message.Gps }
     * 
     */
    public TmsMsg.Transaction.Message.Gps createTmsMsgTransactionMessageGps() {
        return new TmsMsg.Transaction.Message.Gps();
    }

}
