//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.06.24 at 10:22:01 PM IST 
//


package com.hlc.TruckTrackPublisher.domain.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="trans_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="veh_fleet_code" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="veh_radio_code" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="protocol_version" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="packet_code" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="transaction"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="trans_date_time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="date_time_offset" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                   &lt;element name="tkt_code" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *                   &lt;element name="tkt_date_time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="order_code" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
 *                   &lt;element name="truck_code" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                   &lt;element name="employee_code" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
 *                   &lt;element name="message"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="time_offset" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                             &lt;element name="value_uom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="gps"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="utc_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                                       &lt;element name="utctime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *                                       &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="latitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="longitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="satellites" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                                       &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                                       &lt;element name="antenna" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="sitename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="trans_cat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="trans_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="trans_sub_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="trans_origin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="trans_origin_ipaddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="trans_origin_machname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="trans_origin_username" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="time_to_live" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transId",
    "vehFleetCode",
    "vehRadioCode",
    "protocolVersion",
    "packetCode",
    "transaction"
})
@XmlRootElement(name = "tms_msg")
@XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
public class TmsMsg {
    //Attributes
    @XmlAttribute(name = "xmlns:xsd", required = true)
    protected String xsd="http://www.w3.org/2001/XMLSchema";
    @XmlAttribute(name = "xmlns:xsi", required = true)
    protected String xsi="http://www.w3.org/2001/XMLSchema-instance";

    @XmlElement(name = "trans_id", required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)

    @JsonProperty("trans_id")
    protected String transId;
    @XmlElement(name = "veh_fleet_code", required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @JsonProperty("veh_fleet_code")
    protected Object vehFleetCode;
    @XmlElement(name = "veh_radio_code", nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlSchemaType(name = "unsignedByte")
    @JsonProperty("veh_radio_code")
    protected short vehRadioCode;
    @XmlElement(name = "protocol_version", nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlSchemaType(name = "unsignedByte")
    @JsonProperty("protocol_version")
    protected short protocolVersion;
    @XmlElement(name = "packet_code", required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @JsonProperty("packet_code")
    protected Object packetCode;
    @XmlElement(required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected TmsMsg.Transaction transaction;

    /**
     * Gets the value of the transId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransId() {
        return transId;
    }

    /**
     * Sets the value of the transId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransId(String value) {
        this.transId = value;
    }

    /**
     * Gets the value of the vehFleetCode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVehFleetCode() {
        return vehFleetCode;
    }

    /**
     * Sets the value of the vehFleetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVehFleetCode(Object value) {
        this.vehFleetCode = value;
    }

    /**
     * Gets the value of the vehRadioCode property.
     * 
     */
    public short getVehRadioCode() {
        return vehRadioCode;
    }

    /**
     * Sets the value of the vehRadioCode property.
     * 
     */
    public void setVehRadioCode(short value) {
        this.vehRadioCode = value;
    }

    /**
     * Gets the value of the protocolVersion property.
     * 
     */
    public short getProtocolVersion() {
        return protocolVersion;
    }

    /**
     * Sets the value of the protocolVersion property.
     * 
     */
    public void setProtocolVersion(short value) {
        this.protocolVersion = value;
    }

    /**
     * Gets the value of the packetCode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPacketCode() {
        return packetCode;
    }

    /**
     * Sets the value of the packetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPacketCode(Object value) {
        this.packetCode = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link TmsMsg.Transaction }
     *     
     */
    public TmsMsg.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmsMsg.Transaction }
     *     
     */
    public void setTransaction(TmsMsg.Transaction value) {
        this.transaction = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="trans_date_time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="date_time_offset" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *         &lt;element name="tkt_code" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
     *         &lt;element name="tkt_date_time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="order_code" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
     *         &lt;element name="truck_code" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *         &lt;element name="employee_code" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
     *         &lt;element name="message"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="time_offset" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *                   &lt;element name="value_uom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="gps"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="utc_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *                             &lt;element name="utctime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
     *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                             &lt;element name="latitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                             &lt;element name="longitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="satellites" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                             &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                             &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *                             &lt;element name="antenna" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="sitename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="trans_cat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="trans_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="trans_sub_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="trans_origin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="trans_origin_ipaddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="trans_origin_machname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="trans_origin_username" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="time_to_live" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transDateTime",
        "dateTimeOffset",
        "tktCode",
        "tktDateTime",
        "orderCode",
        "truckCode",
        "employeeCode",
        "message",
        "transCat",
        "transType",
        "transSubType",
        "transOrigin",
        "transOriginIpaddr",
        "transOriginMachname",
        "transOriginUsername",
        "timeToLive"
    })
    public static class Transaction {

        @XmlElement(name = "trans_date_time", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_date_time")
        protected String transDateTime;
        @XmlElement(name = "date_time_offset", nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @XmlSchemaType(name = "unsignedByte")
        @JsonProperty("date_time_offset")
        protected short dateTimeOffset;
        @XmlElement(name = "tkt_code", nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @XmlSchemaType(name = "unsignedInt")
        @JsonProperty("tkt_code")
        protected long tktCode;
        @XmlElement(name = "tkt_date_time", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("tkt_date_time")
        protected String tktDateTime;
        @XmlElement(name = "order_code", nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @XmlSchemaType(name = "unsignedShort")
        @JsonProperty("order_code")
        protected int orderCode;
        @XmlElement(name = "truck_code", nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @XmlSchemaType(name = "unsignedByte")
        @JsonProperty("truck_code")
        protected short truckCode;
        @XmlElement(name = "employee_code", nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @XmlSchemaType(name = "unsignedShort")
        @JsonProperty("employee_code")
        protected int employeeCode;
        @XmlElement(required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        protected TmsMsg.Transaction.Message message;
        @XmlElement(name = "trans_cat", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_cat")
        protected String transCat;
        @XmlElement(name = "trans_type", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_type")
        protected String transType;
        @XmlElement(name = "trans_sub_type", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_sub_type")
        protected String transSubType;
        @XmlElement(name = "trans_origin", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_origin")
        protected String transOrigin;
        @XmlElement(name = "trans_origin_ipaddr", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_origin_ipaddr")
        protected String transOriginIpaddr;
        @XmlElement(name = "trans_origin_machname", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_origin_machname")
        protected String transOriginMachname;
        @XmlElement(name = "trans_origin_username", required = true, nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @JsonProperty("trans_origin_username")
        protected String transOriginUsername;
        @XmlElement(name = "time_to_live", nillable = true)
        @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
        @XmlSchemaType(name = "unsignedByte")
        @JsonProperty("time_to_live")
        protected short timeToLive;

        /**
         * Gets the value of the transDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransDateTime() {
            return transDateTime;
        }

        /**
         * Sets the value of the transDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransDateTime(String value) {
            this.transDateTime = value;
        }

        /**
         * Gets the value of the dateTimeOffset property.
         * 
         */
        public short getDateTimeOffset() {
            return dateTimeOffset;
        }

        /**
         * Sets the value of the dateTimeOffset property.
         * 
         */
        public void setDateTimeOffset(short value) {
            this.dateTimeOffset = value;
        }

        /**
         * Gets the value of the tktCode property.
         * 
         */
        public long getTktCode() {
            return tktCode;
        }

        /**
         * Sets the value of the tktCode property.
         * 
         */
        public void setTktCode(long value) {
            this.tktCode = value;
        }

        /**
         * Gets the value of the tktDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTktDateTime() {
            return tktDateTime;
        }

        /**
         * Sets the value of the tktDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTktDateTime(String value) {
            this.tktDateTime = value;
        }

        /**
         * Gets the value of the orderCode property.
         * 
         */
        public int getOrderCode() {
            return orderCode;
        }

        /**
         * Sets the value of the orderCode property.
         * 
         */
        public void setOrderCode(int value) {
            this.orderCode = value;
        }

        /**
         * Gets the value of the truckCode property.
         * 
         */
        public short getTruckCode() {
            return truckCode;
        }

        /**
         * Sets the value of the truckCode property.
         * 
         */
        public void setTruckCode(short value) {
            this.truckCode = value;
        }

        /**
         * Gets the value of the employeeCode property.
         * 
         */
        public int getEmployeeCode() {
            return employeeCode;
        }

        /**
         * Sets the value of the employeeCode property.
         * 
         */
        public void setEmployeeCode(int value) {
            this.employeeCode = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link TmsMsg.Transaction.Message }
         *     
         */
        public TmsMsg.Transaction.Message getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link TmsMsg.Transaction.Message }
         *     
         */
        public void setMessage(TmsMsg.Transaction.Message value) {
            this.message = value;
        }

        /**
         * Gets the value of the transCat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransCat() {
            return transCat;
        }

        /**
         * Sets the value of the transCat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransCat(String value) {
            this.transCat = value;
        }

        /**
         * Gets the value of the transType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransType() {
            return transType;
        }

        /**
         * Sets the value of the transType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransType(String value) {
            this.transType = value;
        }

        /**
         * Gets the value of the transSubType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransSubType() {
            return transSubType;
        }

        /**
         * Sets the value of the transSubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransSubType(String value) {
            this.transSubType = value;
        }

        /**
         * Gets the value of the transOrigin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransOrigin() {
            return transOrigin;
        }

        /**
         * Sets the value of the transOrigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransOrigin(String value) {
            this.transOrigin = value;
        }

        /**
         * Gets the value of the transOriginIpaddr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransOriginIpaddr() {
            return transOriginIpaddr;
        }

        /**
         * Sets the value of the transOriginIpaddr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransOriginIpaddr(String value) {
            this.transOriginIpaddr = value;
        }

        /**
         * Gets the value of the transOriginMachname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransOriginMachname() {
            return transOriginMachname;
        }

        /**
         * Sets the value of the transOriginMachname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransOriginMachname(String value) {
            this.transOriginMachname = value;
        }

        /**
         * Gets the value of the transOriginUsername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransOriginUsername() {
            return transOriginUsername;
        }

        /**
         * Sets the value of the transOriginUsername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransOriginUsername(String value) {
            this.transOriginUsername = value;
        }

        /**
         * Gets the value of the timeToLive property.
         * 
         */
        public short getTimeToLive() {
            return timeToLive;
        }

        /**
         * Sets the value of the timeToLive property.
         * 
         */
        public void setTimeToLive(short value) {
            this.timeToLive = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="time_offset" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
         *         &lt;element name="value_uom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="gps"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="utc_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
         *                   &lt;element name="utctime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
         *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
         *                   &lt;element name="latitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
         *                   &lt;element name="longitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="satellites" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *                   &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
         *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
         *                   &lt;element name="antenna" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="sitename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "timeOffset",
            "type",
            "value",
            "valueUom",
            "gps",
            "sitename"
        })
        public static class Message {

            @XmlElement(name = "time_offset", required = true, nillable = true)
            @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
            @JsonProperty("time_offset")
            protected Object timeOffset;
            @XmlElement(required = true, nillable = true)
            @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
            protected Object type;
            @XmlSchemaType(name = "unsignedByte")
            protected short value;
            @XmlElement(name = "value_uom", required = true, nillable = true)
            @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
            @JsonProperty("value_uom")
            protected String valueUom;
            @XmlElement(required = true, nillable = true)
            @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
            protected TmsMsg.Transaction.Message.Gps gps;
            @XmlElement(required = true, nillable = true)
            @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
            protected String sitename;

            /**
             * Gets the value of the timeOffset property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getTimeOffset() {
                return timeOffset;
            }

            /**
             * Sets the value of the timeOffset property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setTimeOffset(Object value) {
                this.timeOffset = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setType(Object value) {
                this.type = value;
            }

            /**
             * Gets the value of the value property.
             * 
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(short value) {
                this.value = value;
            }

            /**
             * Gets the value of the valueUom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueUom() {
                return valueUom;
            }

            /**
             * Sets the value of the valueUom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueUom(String value) {
                this.valueUom = value;
            }

            /**
             * Gets the value of the gps property.
             * 
             * @return
             *     possible object is
             *     {@link TmsMsg.Transaction.Message.Gps }
             *     
             */
            public TmsMsg.Transaction.Message.Gps getGps() {
                return gps;
            }

            /**
             * Sets the value of the gps property.
             * 
             * @param value
             *     allowed object is
             *     {@link TmsMsg.Transaction.Message.Gps }
             *     
             */
            public void setGps(TmsMsg.Transaction.Message.Gps value) {
                this.gps = value;
            }

            /**
             * Gets the value of the sitename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSitename() {
                return sitename;
            }

            /**
             * Sets the value of the sitename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSitename(String value) {
                this.sitename = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected         content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="utc_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
             *         &lt;element name="utctime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
             *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
             *         &lt;element name="latitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
             *         &lt;element name="longitude_hemi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="satellites" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
             *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
             *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
             *         &lt;element name="antenna" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "utcDateTime",
                "utctime",
                "latitude",
                "latitudeHemi",
                "longitude",
                "longitudeHemi",
                "satellites",
                "speed",
                "heading",
                "antenna"
            })
            public static class Gps {

                @XmlElement(name = "utc_date_time", required = true, nillable = true)
                @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                @XmlSchemaType(name = "dateTime")
                protected String utcDateTime;
                @XmlSchemaType(name = "unsignedInt")
                protected long utctime;
                @XmlElement(required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected BigDecimal latitude;
                @XmlElement(name = "latitude_hemi", required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected String latitudeHemi;
                @XmlElement(required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected BigDecimal longitude;
                @XmlElement(name = "longitude_hemi", required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected String longitudeHemi;
                @XmlElement(required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected Object satellites;
                @XmlElement(required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected BigDecimal speed;
                @XmlSchemaType(name = "unsignedByte")
                protected short heading;
                @XmlElement(required = true, nillable = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
                protected Object antenna;
                @XmlAttribute(name = "version", required = true)
                protected BigDecimal version;

                /**
                 * Gets the value of the utcDateTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public String getUtcDateTime() {
                    return utcDateTime;
                }

                /**
                 * Sets the value of the utcDateTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setUtcDateTime(String value) {
                    this.utcDateTime = value;
                }

                /**
                 * Gets the value of the utctime property.
                 * 
                 */
                public long getUtctime() {
                    return utctime;
                }

                /**
                 * Sets the value of the utctime property.
                 * 
                 */
                public void setUtctime(long value) {
                    this.utctime = value;
                }

                /**
                 * Gets the value of the latitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getLatitude() {
                    return latitude;
                }

                /**
                 * Sets the value of the latitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setLatitude(BigDecimal value) {
                    this.latitude = value;
                }

                /**
                 * Gets the value of the latitudeHemi property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLatitudeHemi() {
                    return latitudeHemi;
                }

                /**
                 * Sets the value of the latitudeHemi property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLatitudeHemi(String value) {
                    this.latitudeHemi = value;
                }

                /**
                 * Gets the value of the longitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getLongitude() {
                    return longitude;
                }

                /**
                 * Sets the value of the longitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setLongitude(BigDecimal value) {
                    this.longitude = value;
                }

                /**
                 * Gets the value of the longitudeHemi property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLongitudeHemi() {
                    return longitudeHemi;
                }

                /**
                 * Sets the value of the longitudeHemi property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLongitudeHemi(String value) {
                    this.longitudeHemi = value;
                }

                /**
                 * Gets the value of the satellites property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getSatellites() {
                    return satellites;
                }

                /**
                 * Sets the value of the satellites property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setSatellites(Object value) {
                    this.satellites = value;
                }

                /**
                 * Gets the value of the speed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getSpeed() {
                    return speed;
                }

                /**
                 * Sets the value of the speed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setSpeed(BigDecimal value) {
                    this.speed = value;
                }

                /**
                 * Gets the value of the heading property.
                 * 
                 */
                public short getHeading() {
                    return heading;
                }

                /**
                 * Sets the value of the heading property.
                 * 
                 */
                public void setHeading(short value) {
                    this.heading = value;
                }

                /**
                 * Gets the value of the antenna property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getAntenna() {
                    return antenna;
                }

                /**
                 * Sets the value of the antenna property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setAntenna(Object value) {
                    this.antenna = value;
                }

                /**
                 * Gets the value of the version property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getVersion() {
                    return version;
                }

                /**
                 * Sets the value of the version property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setVersion(BigDecimal value) {
                    this.version = value;
                }

            }

        }

    }

}
